name: common
version: 0.1.0
description: >-
  Source code common lib
repository: ' '

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: '>=2.1.0 <4.0.0'
  async: ^2.5.0
  build: ^2.1.0
  dart_style: ^2.0.0
  glob: ^2.0.0
  meta: ^1.3.0
  path: ^1.8.0
  source_span: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: '^2.0.0'
  build_verify: ^3.0.0
  build_test: ^2.0.0
  coverage: any # test already depends on it
  json_serializable: ^6.0.1
  source_gen: '^1.0.0'
  xml: ^5.0.0
  term_glyph: ^1.2.0
  test: ^1.16.0